### ISSUE TITLE
-s all参数报错

### ISSUE THREAD

**Issue by monster663** [saucer-man/saucerframe#12]
我想要对url.txt中的链接测试所有的weblogic漏洞，尝试用下面的命令运行Python脚本
python saucerframe.py -iF url.txt -s all
报错信息显示：[-] Script [all.py] not exist. Use [--show] to view all available script in ./scripts/
具体如下：
![image](https://github.com/saucer-man/saucerframe/assets/57214513/b262bca6-b2fa-4230-8c8b-ba077d295c6a)
希望能够找到一个解决方法，o(*￣▽￣*)ブ

**Comment by saucer-man** [comment]
截图全一点看下
