### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Pengyuan-yue** [saucer-man/saucerframe#13]
__  https://saucer-man.com                         
                              / |                         
___  __ _ _   _  ___ ___ _ ___| | _ __ __ _ _ __ ___   ___ 
/ __|/ _` | | | |/ __/ _ \ '__|  _| '__/ _` | '_ ` _ \ / _ \
\__ \ (_| | |_| | (_|  __/ |  | | | | | (_| | | | | | |  __/
|___/\__,_|\__,_|\___\___|_|  |_| |_|  \__,_|_| |_| |_|\___|                                                                                                

[-] Use -s to load script. Example: [-s spider] or [-s ./script/spider.py]

[*] shutting down at 08:35:44

**Comment by saucer-man** [comment]
?

**Comment by Pengyuan-yue** [comment]
是国人那就直接说了，我用命令行打开会删一个运行库，然后运行库自己就关了，用pycharm打开就这样

**Comment by saucer-man** [comment]
什么是删除一个运行库，能贴一点更详细的日志或者截图看看吗
